# Generated by Django 4.1.5 on 2023-02-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="حذف شده/حذف نشده"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, default="", unique=True, verbose_name="عنوان در url"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=300, verbose_name="نام محصول"),
        ),
    ]
